// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOG9Kw40GeJpOO6_qxKyWjoHKlklO7wOU',
    appId: '1:510780556481:web:6f252fb6981d196ffa0040',
    messagingSenderId: '510780556481',
    projectId: 'examendisonia',
    authDomain: 'examendisonia.firebaseapp.com',
    storageBucket: 'examendisonia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-b_jgZoVRwp7PfFN_8DhJdGKg7vco8zs',
    appId: '1:510780556481:android:f24144f81802f1e8fa0040',
    messagingSenderId: '510780556481',
    projectId: 'examendisonia',
    storageBucket: 'examendisonia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZTGpwQ0yeWgux4CGPoMNa9F1usLqPl0A',
    appId: '1:510780556481:ios:ef9ff355f87f7420fa0040',
    messagingSenderId: '510780556481',
    projectId: 'examendisonia',
    storageBucket: 'examendisonia.appspot.com',
    iosClientId: '510780556481-k741c0f7e65lsp0lo7krm8lpqc6qkakc.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
